#!/bin/bash
#
# ./download
#

. ./env

echo "Downloading JJ2..."
urls=(
	"http://www.jazzjackrabbit.net/other_files/Jazz%20Jackrabbit%202.zip"
	"http://www.bestoldgames.net/download/bgames/jazz-jackrabbit-2.zip"
	"http://files.abandonia.com/download.php?game=Jazz+Jackrabbit+2&secure=ce95c11a306aa2eeaadff7b0e973e3fa&td=1304618652"
)
aria2c -j1 -s1 -m1 -c -R --connect-timeout=30 -o "dl/jj2.zip" ${urls[@]}


echo "Downloading AutoHotkey..."
ahkurl="https://autohotkey.com/download/ahk-u32.zip"
aria2c -j1 -s1 -m1 -c -R --connect-timeout=30 -o "dl/ahk.zip" "$ahkurl"

# unzip it
unzip -q -o "dl/ahk.zip" "AutoHotkey.exe" -d utils


echo "Downloading jj2-bridge..."
bridgeurl="https://github.com/daniel-j/jj2-bridge/releases/download/0.0.2/release.zip"
aria2c -j1 -s1 -m1 -c -R --connect-timeout=30 -o "dl/jj2-bridge.zip" "$bridgeurl"

# unzip it
unzip -q -o "dl/jj2-bridge.zip" "jj2-bridge.exe" -d utils
