#!/bin/bash

path="$1"
skel="${2-skel}"

# if it's a new directory, copy the skeleton
if [ ! -d "$path" ]
then
	mkdir -p "$path"
	echo "Initializing wine prefix..."
	wineboot --init
	echo "Copying skeleton to $1..."
	cp -nrv "$skel/." "$path/"
fi
