#!/bin/bash
# you can run this to update plus too
# updating will not run plusifier again, only replace files

. ./env

path=$(pwd)

echo "Downloading JJ2 Plus..."

mkdir -p dl

plusurl="http://www.jazz2online.com/jj2plus/plus.zip"
aria2c -j1 -s1 -m1 -c -R --connect-timeout=30 -o "dl/plus.zip" "$plusurl"

echo "Extracting JJ2 Plus..."
unzip -q -o "dl/plus.zip" -d game

if [ ! -f "game/Jazz2+.exe" ]; then
	echo "Patching JJ2 with plusifier..."

	cd game
	rm -f "Jazz2+.exe"

	echo no | "$path/xvfb-run" "$path/ahk/ahk" "$path/ahk/plusifier.ahk" "plusifier.exe" #&> /dev/null

	
else
	echo "Skipping plusifier, JJ2 is already plusified."
fi
