#!/bin/bash

. ./env

path="$1"
extraflags="${@:2}"

if [ -z "$path" ]; then
	path="game"
fi

exe="$path/Jazz2+.exe"
flags="-windowed -menu -nolog -nospy -noddrawwin -noddraw -noddrawmemcheck -nojoy -noerrtrap -nocpucheck $extraflags"

if [ ! -f "$exe" ]; then
	echo "$exe not found"
	exit 1
fi

echo "Launching $exe $flags"
echo "Running in wine prefix $WINEPREFIX"

wine start /wait "$exe" $flags
