#!/bin/bash
#
# ./start <gamedir> <flags>
# gamedir defaults to 'game'
#
. ./env

path="$1"
extraflags="${@:2}"

if [ -z "$path" ]
then
	path="game"
fi

exe="$path/Jazz2+.exe"
flags="-windowed -menu -nolog -nospy -noddrawmemcheck -noerrtrap $extraflags"

if [ ! -f "$exe" ]
then
	echo "$exe not found"
	exit 1
fi

echo "Launching $exe $flags"
echo "Running in wine prefix $WINEPREFIX"

exec wine "$exe" $flags
