#!/bin/bash
#
# You should run this with ./xvfb-run if you don't have an X server
# ./xvfb-run ./startded <gamedir> <flags>
#

. ./env

path="$1"
extraflags="${@:2}"

export WINEPREFIX="$(pwd)/$path/.wine"

echo "Starting dedicated JJ2 server $1"

# if it's a new directory, copy the skeleton
if [ ! -d "$path" ]; then
	mkdir -p "$path"
	. ./initskeleton "$path"
fi

# always attempt to link
./link "$path"

if [ -f "$path/startup.reg" ]; then
	echo "Applying startup.reg"
	regedit /C "$path/startup.reg"
fi

exec ./start "$path" -nocpucheck -nosound -server "$extraflags"
