#!/bin/bash
#
# You should run this with ./xvfb-run if you don't have an X server
# ./xvfb-run ./startded <gamedir> <flags>
#

. ./env

path="$1"
extraflags="${@:2}"

export WINEPREFIX="$(pwd)/$path/.wine"

echo "Starting dedicated JJ2 server $1"

trap 'stopserver' INT

stopserver() {
    trap '' INT TERM     # ignore INT and TERM while shutting down
    echo "**** Shutting down... ****"     # added double quotes
    kill -TERM 0         # fixed order, send TERM not INT
    wait
    echo "Done."
}

# if it's a new directory, copy the skeleton
if [ ! -d "$path" ]
then
	mkdir -p "$path"
	wineboot
	./initskeleton "$path"
fi

# always attempt to link
./link "$path"

if [ -f "$path/startup.reg" ]
then
	echo "Applying startup.reg"
	regedit "$path/startup.reg"
fi

initcommands=$(cat $path/startup.txt 2> /dev/null | grep -v '^;')

touch "$path/chatlog001.txt" "$path/playlog001.txt" "$path/iplog001.txt"

# check if chatlog file is in use. if it is, abort
chatlogfile=$(realpath "$path/chatlog001.txt")
ischatloggeropen=$(lsof | grep -F "$chatlogfile" | wc -l)

if [ "$ischatloggeropen" -gt "0" ]
then
	echo "Error: A program is already accessing $path/chatlog001.txt"
	exit 1
fi

# Start JJ2!
(./start "$path" -nocpucheck -nosound -server "$extraflags"; stopserver) &

# Show chatlog, playlog and iplog output to stdout. Does not show all characters
(tail -f -n0 --quiet "$path/chatlog001.txt" "$path/playlog001.txt" "$path/iplog001.txt"; stopserver) &

# stdin! Send chat and plus commands. Does not support all characters
# send /close to cleanly shut down the JJ2 server by closing its window (Windows API)
(echo -e "$initcommands" && cat) | wine utils/jj2-bridge.exe

wait
